"""
Created on Fri Mar  7 16:58:55 2014

@author: zoherghadyali, jaywoo, sophiali
"""

world = [[
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W            W                    W",
        "W            W                  C W",
        "W    W       W      WWWWWWWWWWWWWWW",
        "W    W       W                    W",
        "W    W                            W",
        "W    W                            W",
        "W    W                            W",
        "W    W                            W",
        "W    W           WWWWWWWWWWWWWWWWWW",
        "W    W                            W",
        "W    W                            W",
        "W    W                            W",
        "W    W                            W",
        "W    W                            W",
        "W    Wwwwwwwwwwwwwww              W",
        "W                                 W",
        "W      WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W      W                          W",
        "W      WWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                              W  W",
        "W                              W  W",
        "W         WWWWWWWWWWWWWWWWWWWWWW  W",
        "W                                 W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        ],
        [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W    W                      W     W",
        "W    W                      W     W",
        "W    W                      W     W",
        "W    W                      W     W",
        "W    W  C                   W     W",
        "W    WWWWWWWWWWWWW          W     W",
        "W                           W     W",
        "W                           W     W",
        "W                W          W     W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W   WWWWWWWWWWWWWW",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        ],
                [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W                W                W",
        "W                W                W",
        "WWWWWWWWWWWWW    W        W       W",
        "W                W        W       W",
        "W                W        W       W",
        "W    WWWWWWWWWWWWW        W       W",
        "W                         W       W",
        "W                         W       W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWW       W",
        "W                                 W",
        "W                                 W",
        "W                                 W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W                W                W",
        "W  C             W                W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        ],
                [
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W                                 W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW     W",
        "W         WWWWWWWWWWWWWWWWWWW   C W",
        "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
        ]
        
        ]